<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exercício Aula 5 - VAR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Exercício Aula 5 - VAR_files/libs/clipboard/clipboard.min.js"></script>
<script src="Exercício Aula 5 - VAR_files/libs/quarto-html/quarto.js"></script>
<script src="Exercício Aula 5 - VAR_files/libs/quarto-html/popper.min.js"></script>
<script src="Exercício Aula 5 - VAR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Exercício Aula 5 - VAR_files/libs/quarto-html/anchor.min.js"></script>
<link href="Exercício Aula 5 - VAR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Exercício Aula 5 - VAR_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Exercício Aula 5 - VAR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Exercício Aula 5 - VAR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Exercício Aula 5 - VAR_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercício Aula 5 - VAR</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>RAFAEL DA SILVA, GUSTAVO JOSE MAZZOTTI MARTINS, CESAR AFONSO APARECIDO </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<table class="caption-top table">
<colgroup>
<col style="width: 63%">
<col style="width: 36%">
</colgroup>
<tbody>
<tr class="odd">
<td><img src="contextual%20learning%20experience%20logo.png" class="img-fluid"></td>
<td style="text-align: right;"><img src="FGV%20EESP%20Logo.png" class="img-fluid"></td>
</tr>
</tbody>
</table>
<section id="motivação" class="level2">
<h2 class="anchored" data-anchor-id="motivação">Motivação</h2>
<p>Suponha que você seja um analista em uma instituição financeira responsável por desenvolver estratégias de captação de recursos e planejamento de funding.</p>
<p>Uma das principais preocupações do banco é garantir uma base sólida de depósitos, que constitui uma importante fonte de recursos para financiar suas operações.</p>
<p>Sua tarefa é utilizar um modelo VAR para analisar as relações entre variáveis macroeconômicas e os depósitos totais.</p>
<p>O objetivo é prever como diferentes choques econômicos podem impactar esses depósitos, auxiliando o banco a planejar estratégias de captação e alocação de recursos de maneira eficiente.</p>
<p>Sua análise fornecerá uma perspectiva sobre o crescimento potencial dos depósitos no mercado, o que permitirá à instituição estimar o volume de funding que poderá captar e, assim, realizar um planejamento estratégico informado, fundamentando as decisões de curto e médio prazo.</p>
</section>
<section id="exercício" class="level2">
<h2 class="anchored" data-anchor-id="exercício">Exercício</h2>
<p>Considerando as séries trimestrais dos Depósitos Totais, PIB, Selic, IPCA e Desemprego, entre 2013 e 2024, realize as atividades descritas a seguir.</p>
<p>Carregando as bibliotecas necessárias</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)          <span class="co"># Manipulação de dados em tabelas de dados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)          <span class="co"># Manipulação de dados em tabelas de dados</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)     <span class="co"># Manipulação de dados em tabelas de dados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'data.table'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:dplyr':

    between, first, last</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GetBCBData)     <span class="co"># Acesso aos dados do Banco Central do Brasil</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sidrar)         <span class="co"># Acesso aos dados do IBGE/SIDRA</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)            <span class="co"># Manipulação de séries temporais</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:data.table':

    yearmon, yearqtr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Os seguintes objetos são mascarados por 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)        <span class="co"># Manipulação de séries temporais</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)        <span class="co"># Manipulação de gráficos</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(urca)           <span class="co"># Execução de testes estatísticos</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vars)           <span class="co"># Estimar modelos VAR</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>O seguinte objeto é mascarado por 'package:dplyr':

    select</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: strucchange</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: sandwich</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: lmtest</code></pre>
</div>
</div>
<p>Obtendo os dados do Banco Central do Brasil</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dados_bacen <span class="ot">=</span> <span class="fu">data.table</span>(<span class="fu">gbcbd_get_series</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="fu">c</span>(<span class="at">Selic =</span> <span class="dv">4189</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">IPCA_12M =</span> <span class="dv">13522</span>, </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Desemprego =</span> <span class="dv">24369</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Dep_Vista =</span> <span class="dv">27790</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">Dep_Poup =</span> <span class="dv">1835</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Dep_Prazo =</span> <span class="dv">27805</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">first.date =</span> <span class="st">"2010-01-01"</span>, <span class="co">#Data inicial dos dados</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">last.date =</span> <span class="st">"2024-03-31"</span>,  <span class="co">#Data final dos dados</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">format.data =</span> <span class="st">"wide"</span>       <span class="co">#Formato dos dados em colunas separadas</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Fetching Selic [4189] from BCB-SGS with cache 
     Found 171 observations
Fetching IPCA_12M [13522] from BCB-SGS with cache 
     Found 171 observations
Fetching Desemprego [24369] from BCB-SGS with cache 
     Found 145 observations
Fetching Dep_Vista [27790] from BCB-SGS with cache 
     Found 171 observations
Fetching Dep_Poup [1835] from BCB-SGS with cache 
     Found 171 observations
Fetching Dep_Prazo [27805] from BCB-SGS with cache 
     Found 171 observations</code></pre>
</div>
</div>
<ul>
<li><p>Extraindo o último dia de cada mês para cada série</p></li>
<li><p>Preenchendo os valores NA com o último valor não-NA disponível</p></li>
<li><p>Mantendo apenas o último dia de cada mês</p></li>
<li><p>Convertendo a data para o formato ano-mês</p></li>
<li><p>Realizando um filtro para manter apenas os últimos dias de março, junho, setembro e dezembro</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Adiciona a Coluna Data para futuras operações</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>dados_bacen[, Data<span class="sc">:</span><span class="er">=</span> ref.date]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Preenche valores NA com o último valor não-NA disponivel</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>dados_bacen <span class="ot">=</span> dados_bacen[, <span class="fu">lapply</span>(.SD, <span class="cf">function</span>(x){zoo<span class="sc">::</span><span class="fu">na.locf</span>(x, <span class="at">fromLast =</span> <span class="cn">FALSE</span>)})]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in as.data.table.list(jval, .named = NULL): Item 4 has 145 rows but
longest item has 171; recycled with remainder.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Mantem apenas o último dia de cada mês</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dados_bacen <span class="ot">=</span> dados_bacen[, .SD[.N], by <span class="ot">=</span> .(<span class="fu">year</span>(ref.date),<span class="fu">month</span>(ref.date))]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Converte a data para o formato ano-mês</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>dados_bacen[, Data <span class="sc">:</span><span class="er">=</span> <span class="fu">as.yearmon</span>(Data)]</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Filtra para manter apenas os últimos dias de março, junho, setembro e dezembro</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>dados_bacen <span class="ot">=</span> dados_bacen[month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">9</span>,<span class="dv">12</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p>Calculando os depósitos totais</p></li>
<li><p>Calculando a variação anual (year-over-year) dos depósitos totais</p></li>
<li><p>calculando a variação anual do desemprego</p></li>
<li><p>Calculando a diferença anual do IPCA (inflação)</p></li>
<li><p>Calculando a diferença logarítmica da taxa Selic</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Somando todos os tipos de depósitos</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>dados_bacen[, Dep_Total <span class="sc">:</span><span class="er">=</span> Dep_Vista <span class="sc">+</span> Dep_Prazo <span class="sc">+</span> Dep_Poup]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Criando coluna com a variação year-over-year dos depósitos</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>dados_bacen[, Dep_Total_yoy <span class="sc">:</span><span class="er">=</span> ((Dep_Total<span class="sc">/</span>dplyr<span class="sc">::</span><span class="fu">lag</span>(Dep_Total,<span class="dv">4</span>))<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="dv">100</span>]</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculando a variação anual da taxa de desemprego</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>dados_bacen[, Desemprego_yoy <span class="sc">:</span><span class="er">=</span> ((Desemprego<span class="sc">/</span>dplyr<span class="sc">::</span><span class="fu">lag</span>(Desemprego,<span class="dv">4</span>))<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="dv">100</span>]</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculando a diferença anual do IPCA (Inflação)</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>dados_bacen[, IPCA_12M_diff <span class="sc">:</span><span class="er">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(IPCA_12M))]</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculando a diferença logarítmica da taxa Selic</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>dados_bacen[, Selic_diff <span class="sc">:</span><span class="er">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(<span class="fu">log</span>(Selic)))]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Obtendo os dados do PIB do IBGE / SIDRA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pib_yoy <span class="ot">=</span> <span class="fu">data.table</span>(<span class="fu">get_sidra</span>(<span class="at">api =</span> <span class="st">"/t/5932/n1/all/v/6561/p/all/c11255/90707/d/v6561%201"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>All others arguments are desconsidered when 'api' is informed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Renomeando as colunas e formatando as colunas de datas</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>pib_yoy <span class="ot">=</span> pib_yoy[, .(<span class="at">Data =</span> <span class="st">`</span><span class="at">Trimestre (Código)</span><span class="st">`</span>, <span class="at">PIB_yoy =</span> Valor)]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>pib_yoy[, Data<span class="sc">:</span><span class="er">=</span> <span class="fu">as.yearmon</span>(<span class="fu">paste0</span>(<span class="fu">substr</span>(Data,<span class="dv">1</span>,<span class="dv">4</span>),<span class="st">"-"</span>,<span class="fu">as.numeric</span>(<span class="fu">substr</span>(Data, <span class="dv">6</span>, <span class="dv">6</span>))<span class="sc">*</span><span class="dv">3</span>))]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mesclando os dados do PIB com os dados do Banco Central</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>data_macro <span class="ot">=</span> pib_yoy[dados_bacen, on <span class="ot">=</span> <span class="st">"Data"</span>]</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Removendo colunas auxiliares nao necessárias</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>data_macro[, year <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>data_macro[, month <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Filtrando os dados para o periodo apos março de 2013</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>data_macro <span class="ot">=</span> data_macro[Data <span class="sc">&gt;=</span> <span class="st">"mar 2013"</span>, .(Data, Dep_Total_yoy, PIB_yoy, Desemprego_yoy, Selic_diff, IPCA_12M_diff)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Garantindo que os valores da coluna Data sejam um formato de data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data_macro[, Data <span class="sc">:</span><span class="er">=</span> <span class="fu">as.Date</span>(<span class="fu">as.yearmon</span>(Data))]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Transformando os dados para o formato longo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>data_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(data_macro,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">cols =</span> <span class="sc">-</span>Data,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">names_to =</span> <span class="st">"Variable"</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">values_to =</span> <span class="st">"Value"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plotando os Gráficos das Séries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_long, <span class="fu">aes</span>(<span class="at">x =</span> Data, <span class="at">y =</span> Value, <span class="at">group =</span> Variable, <span class="at">color =</span> Variable)) <span class="sc">+</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Variable, <span class="at">scales =</span> <span class="st">"free_y"</span> , <span class="at">ncol =</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="co">#Ajuste o numero #das colunas</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_x_date</span>(</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">date_breaks</span>(<span class="st">"1 year"</span>), <span class="co">#Ajuste Intervalo dos Rotulos</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">date_format</span>(<span class="st">"%Y"</span>) <span class="co"># Formatacao dos Rotulos</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a> ) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tempo"</span>, <span class="at">y =</span> <span class="st">"Valor"</span>, <span class="at">title =</span> <span class="st">"Series Temporais com Eixos Separados"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercício-Aula-5---VAR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="agora-que-as-séries-foram-carregadas-ajustadas-e-visualizadas-vamos-prosseguir-com-as-seguintes-análises" class="level2">
<h2 class="anchored" data-anchor-id="agora-que-as-séries-foram-carregadas-ajustadas-e-visualizadas-vamos-prosseguir-com-as-seguintes-análises">1 -) Agora que as séries foram carregadas, ajustadas e visualizadas, vamos prosseguir com as seguintes análises:</h2>
<section id="a.-verifique-se-as-séries-temporais-das-variáveis-macroeconômicas-são-estacionárias." class="level3">
<h3 class="anchored" data-anchor-id="a.-verifique-se-as-séries-temporais-das-variáveis-macroeconômicas-são-estacionárias.">a. Verifique se as séries temporais das variáveis macroeconômicas são estacionárias.</h3>
<ul>
<li><p>Utilize o teste ADF com a função adf.test(), o teste KPSS com a função ur.kpss(), e o teste</p></li>
<li><p>Phillips-Perron com a função pp.test().</p></li>
<li><p>Apresente os resultados dos testes e discuta as transformações aplicadas.</p></li>
</ul>
<p><strong>Função para Aplicação do Teste ADF nas séries</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>apply_adf <span class="ot">&lt;-</span> <span class="cf">function</span>(data, var) {</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(<span class="fu">na.omit</span>(data[[var]]))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  p_value <span class="ot">&lt;-</span> result<span class="sc">$</span>p.value</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Decidindo se a série e estacionária com base no p-valor</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  stationary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Sim"</span>,<span class="st">"Não"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">data.table</span>(<span class="at">variable =</span> var, <span class="at">test =</span> <span class="st">"ADF"</span>, <span class="at">p_value =</span> p_value, <span class="at">stationary =</span> stationary))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Função para aplicação do teste KPSS</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>apply_kpss <span class="ot">&lt;-</span> <span class="cf">function</span>(data, var){</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">ur.kpss</span>(<span class="fu">na.omit</span>(data[[var]]), <span class="at">type =</span> <span class="st">"mu"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  p_value <span class="ot">&lt;-</span> result<span class="sc">@</span>teststat</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  critical_value <span class="ot">&lt;-</span> result<span class="sc">@</span>cval[<span class="dv">2</span>]</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  stationary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> critical_value, <span class="st">"Não"</span>,<span class="st">"Sim"</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">data.table</span>(<span class="at">variable =</span> var, <span class="at">test =</span> <span class="st">"KPSS"</span>, <span class="at">p_value =</span> p_value, <span class="at">stationary =</span> stationary))</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Função para Aplicação do teste Phillips-Perron</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>apply_pp <span class="ot">&lt;-</span> <span class="cf">function</span>(data, var){</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">pp.test</span>(<span class="fu">na.omit</span>(data[[var]]))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  p_value <span class="ot">&lt;-</span> result<span class="sc">$</span>p.value</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  stationary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Sim"</span>, <span class="st">"Não"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">data.table</span>(<span class="at">variable =</span> var, <span class="at">test =</span> <span class="st">"PP"</span>, <span class="at">p_value =</span> p_value, <span class="at">stationary =</span> stationary))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>colunas <span class="ot">&lt;-</span> <span class="fu">names</span>(data_macro)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(colunas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Data"           "Dep_Total_yoy"  "PIB_yoy"        "Desemprego_yoy"
[5] "Selic_diff"     "IPCA_12M_diff" </code></pre>
</div>
</div>
<p><strong>Aplicando os testes ADF, KPSS e PP na variável “Dep_Total_yoy”, podemos verificar que esta serie é não estacionária.</strong></p>
<p><strong>Para ajustar, vamos aplicar a diferenciação e realizar os testes novamente.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"Dep_Total_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        variable   test   p_value stationary
          &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Dep_Total_yoy    ADF 0.3970014        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"Dep_Total_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        variable   test   p_value stationary
          &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Dep_Total_yoy   KPSS 0.4631922        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"Dep_Total_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        variable   test   p_value stationary
          &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Dep_Total_yoy     PP 0.4061624        Não</code></pre>
</div>
</div>
<p><strong>Aplicando a diferenciação no campo “Dep_Total_yoy”</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculando a diferença no campo "Dep_Total_yoy"</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>data_macro[, Dep_Total_yoy_diff <span class="sc">:</span><span class="er">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(Dep_Total_yoy))]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Aplicando os testes novamente, podemos confirmar a estacionariedade da série.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"Dep_Total_yoy_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in adf.test(na.omit(data[[var]])): p-value smaller than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             variable   test p_value stationary
               &lt;char&gt; &lt;char&gt;   &lt;num&gt;     &lt;char&gt;
1: Dep_Total_yoy_diff    ADF    0.01        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"Dep_Total_yoy_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             variable   test    p_value stationary
               &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: Dep_Total_yoy_diff   KPSS 0.05010198        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"Dep_Total_yoy_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             variable   test    p_value stationary
               &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: Dep_Total_yoy_diff     PP 0.04661052        Sim</code></pre>
</div>
</div>
<p><strong>Aplicando os testes ADF, KPSS e PP na variável “PIB_yoy” podemos avaliar que os testes ADF e PP indicam que a série é estacionária.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"PIB_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   variable   test    p_value stationary
     &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1:  PIB_yoy    ADF 0.04399674        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"PIB_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   variable   test   p_value stationary
     &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1:  PIB_yoy   KPSS 0.2828691        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"PIB_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   variable   test    p_value stationary
     &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1:  PIB_yoy     PP 0.04888891        Sim</code></pre>
</div>
</div>
<p><strong>Aplicando os testes ADF, KPSS e PP na variável “Desemprego_yoy”, podemos verificar que esta série é não estacionária de acordo com os resultados dos testes ADF e PP. Vamos aplicar a diferenciação nesta série e realizar novamente o teste.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"Desemprego_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         variable   test   p_value stationary
           &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Desemprego_yoy    ADF 0.1467599        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"Desemprego_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         variable   test   p_value stationary
           &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Desemprego_yoy   KPSS 0.6217907        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"Desemprego_yoy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         variable   test   p_value stationary
           &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Desemprego_yoy     PP 0.4753556        Não</code></pre>
</div>
</div>
<p><strong>Aplicando a diferenciação na no campo “Desemprego_yoy”</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculando a diferença no campo "Desemprego_yoy"</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>data_macro[, Desemprego_yoy_diff <span class="sc">:</span><span class="er">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(Desemprego_yoy))]</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Aplicando os testes ADF, KPSS e PP na série diferenciada</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"Desemprego_yoy_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              variable   test   p_value stationary
                &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Desemprego_yoy_diff    ADF 0.0190015        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"Desemprego_yoy_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              variable   test    p_value stationary
                &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: Desemprego_yoy_diff   KPSS 0.05412163        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"Desemprego_yoy_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              variable   test    p_value stationary
                &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: Desemprego_yoy_diff     PP 0.03847687        Sim</code></pre>
</div>
</div>
<p><strong>Após a diferenciação a série se tornou estacionária</strong></p>
<p><strong>Aplicando os testes ADF, KPSS e PP na variável “Selic_diff”, podemos rejeitar a hipótese nula, portanto a série não possui raiz unitária, sendo assim estacionária.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"Selic_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     variable   test    p_value stationary
       &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: Selic_diff    ADF 0.04339006        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"Selic_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     variable   test    p_value stationary
       &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: Selic_diff   KPSS 0.09921993        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"Selic_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     variable   test   p_value stationary
       &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: Selic_diff     PP 0.2979604        Não</code></pre>
</div>
</div>
<p><strong>Aplicando os testes ADF, KPSS e PP na variável “IPCA_12M_diff”</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_adf</span>(data_macro,<span class="st">"IPCA_12M_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        variable   test   p_value stationary
          &lt;char&gt; &lt;char&gt;     &lt;num&gt;     &lt;char&gt;
1: IPCA_12M_diff    ADF 0.0158995        Sim</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_kpss</span>(data_macro,<span class="st">"IPCA_12M_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        variable   test    p_value stationary
          &lt;char&gt; &lt;char&gt;      &lt;num&gt;     &lt;char&gt;
1: IPCA_12M_diff   KPSS 0.06256147        Não</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_pp</span> (data_macro,<span class="st">"IPCA_12M_diff"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pp.test(na.omit(data[[var]])): p-value smaller than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        variable   test p_value stationary
          &lt;char&gt; &lt;char&gt;   &lt;num&gt;     &lt;char&gt;
1: IPCA_12M_diff     PP    0.01        Sim</code></pre>
</div>
</div>
</section>
<section id="b.-com-as-séries-estacionárias-determine-a-ordem-ótima-do-modelo-var-utilizando-a-função" class="level3">
<h3 class="anchored" data-anchor-id="b.-com-as-séries-estacionárias-determine-a-ordem-ótima-do-modelo-var-utilizando-a-função">b. Com as séries estacionárias, determine a ordem ótima do modelo VAR utilizando a função</h3>
<ul>
<li><p>VARselect() para avaliar os critérios de informação como AIC e BIC.</p></li>
<li><p>Considere também a parcimônia do modelo ao escolher a ordem final.</p></li>
<li><p>Explique a escolha da ordem do modelo e como os critérios de informação influenciaram essa decisão.</p></li>
</ul>
<p>Removendo as colunas sem os valores diferenciados e realizando ajustes no dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>data_macro_filtered <span class="ot">&lt;-</span><span class="fu">na.omit</span>(data_macro[, <span class="fu">c</span>(<span class="st">"Data"</span>, <span class="st">"PIB_yoy"</span>, <span class="st">"Selic_diff"</span>, <span class="st">"IPCA_12M_diff"</span>, <span class="st">"Dep_Total_yoy_diff"</span>, <span class="st">"Desemprego_yoy_diff"</span>)])</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Remover a coluna de Data se ela for não numérica</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>data_macro_filtered_numeric <span class="ot">&lt;-</span> data_macro_filtered <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Plotando todas as séries após a diferenciação:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>data_long_2 <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(data_macro_filtered,</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">cols =</span> <span class="sc">-</span>Data,</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">names_to =</span> <span class="st">"Variable"</span>,</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_long_2, <span class="fu">aes</span>(<span class="at">x =</span> Data, <span class="at">y =</span> Value, <span class="at">group =</span> Variable, <span class="at">color =</span> Variable)) <span class="sc">+</span> </span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Variable, <span class="at">scales =</span> <span class="st">"free_y"</span> , <span class="at">ncol =</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="co">#Ajuste o numero #das colunas</span></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_x_date</span>(</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>   <span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">date_breaks</span>(<span class="st">"1 year"</span>), <span class="co">#Ajuste Intervalo dos Rotulos</span></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>   <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">date_format</span>(<span class="st">"%Y"</span>) <span class="co"># Formatacao dos Rotulos</span></span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a> ) <span class="sc">+</span></span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tempo"</span>, <span class="at">y =</span> <span class="st">"Valor"</span>, <span class="at">title =</span> <span class="st">"Series Temporais com Eixos Separados"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercício-Aula-5---VAR_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Executando o VARselect e analisando o resultado:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>mdl_var_aic <span class="ot">&lt;-</span> <span class="fu">VARselect</span>(data_macro_filtered_numeric, <span class="at">lag.max =</span> <span class="dv">5</span>, <span class="at">type =</span> <span class="st">"const"</span>)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdl_var_aic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$selection
AIC(n)  HQ(n)  SC(n) FPE(n) 
     5      5      1      5 

$criteria
               1         2         3        4          5
AIC(n)  3.529786  3.490400  2.666466 1.233355 -0.0938742
HQ(n)   3.988918  4.332142  3.890818 2.840317  1.8956978
SC(n)   4.809449  5.836448  6.078900 5.712175  5.4513313
FPE(n) 34.539351 35.480371 18.598788 6.479243  3.6206324</code></pre>
</div>
</div>
<p><strong>Analisando o resultado podemos extrair os seguintes insights:</strong></p>
<p>Quanto mais lags incluimos no range de estimacao do VARselect, maior os lags sugeridos pelos testes.</p>
<p>Seguindo a premissa de tentarmos estimar um modelo mais parcimonioso possivel, selecionamos 5 lags, pois com esta quantidade de lags, o criterio BIC sugere apenas 1 lag para estimarmos o modelo.</p>
<ul>
<li><p>Critérios de seleção Akaike, Hannan-Quinn e FPE indicam um modelo com 5 lags</p></li>
<li><p>O critério SC(n) Schwars (BIC) indica um modelo com 1 lag.</p></li>
</ul>
<p><strong>Vamos estimar 3 modelos, um considerando os 5 lags sugeridos pela maioria dos critérios de seleção, um considerando 2 lags e 1 considerando apenas 1 lag, e vamos comparar os resultados.</strong></p>
<ul>
<li><strong>Estimando um modelo VAR(1)</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>var_1lag <span class="ot">&lt;-</span> <span class="fu">VAR</span>(data_macro_filtered_numeric, <span class="at">p =</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"none"</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(var_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
VAR Estimation Results:
========================= 
Endogenous variables: PIB_yoy, Selic_diff, IPCA_12M_diff, Dep_Total_yoy_diff, Desemprego_yoy_diff 
Deterministic variables: none 
Sample size: 43 
Log Likelihood: -346.388 
Roots of the characteristic polynomial:
0.7684 0.6196 0.5568 0.5568 0.1026
Call:
VAR(y = data_macro_filtered_numeric, p = 1, type = "none")


Estimation results for equation PIB_yoy: 
======================================== 
PIB_yoy = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 

                       Estimate Std. Error t value Pr(&gt;|t|)   
PIB_yoy.l1              0.43910    0.14779   2.971  0.00512 **
Selic_diff.l1          -5.21899    3.38871  -1.540  0.13182   
IPCA_12M_diff.l1       -0.36346    0.34686  -1.048  0.30133   
Dep_Total_yoy_diff.l1  -0.32225    0.14385  -2.240  0.03101 * 
Desemprego_yoy_diff.l1  0.16666    0.05683   2.933  0.00567 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 2.588 on 38 degrees of freedom
Multiple R-Squared: 0.5246, Adjusted R-squared: 0.462 
F-statistic: 8.386 on 5 and 38 DF,  p-value: 2.038e-05 


Estimation results for equation Selic_diff: 
=========================================== 
Selic_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 

                        Estimate Std. Error t value Pr(&gt;|t|)    
PIB_yoy.l1             -0.009169   0.004729  -1.939 0.059964 .  
Selic_diff.l1           0.558762   0.108435   5.153 8.23e-06 ***
IPCA_12M_diff.l1        0.015639   0.011099   1.409 0.166966    
Dep_Total_yoy_diff.l1  -0.013224   0.004603  -2.873 0.006621 ** 
Desemprego_yoy_diff.l1  0.006709   0.001818   3.690 0.000701 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 0.08282 on 38 degrees of freedom
Multiple R-Squared: 0.7979, Adjusted R-squared: 0.7713 
F-statistic: 30.01 on 5 and 38 DF,  p-value: 3.177e-12 


Estimation results for equation IPCA_12M_diff: 
============================================== 
IPCA_12M_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 

                       Estimate Std. Error t value Pr(&gt;|t|)
PIB_yoy.l1             -0.08785    0.07601  -1.156    0.255
Selic_diff.l1          -0.92667    1.74286  -0.532    0.598
IPCA_12M_diff.l1        0.10300    0.17840   0.577    0.567
Dep_Total_yoy_diff.l1  -0.12131    0.07398  -1.640    0.109
Desemprego_yoy_diff.l1  0.02074    0.02923   0.710    0.482


Residual standard error: 1.331 on 38 degrees of freedom
Multiple R-Squared: 0.1376, Adjusted R-squared: 0.02415 
F-statistic: 1.213 on 5 and 38 DF,  p-value: 0.3218 


Estimation results for equation Dep_Total_yoy_diff: 
=================================================== 
Dep_Total_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 

                        Estimate Std. Error t value Pr(&gt;|t|)    
PIB_yoy.l1              0.302796   0.213980   1.415 0.165191    
Selic_diff.l1           2.064378   4.906456   0.421 0.676310    
IPCA_12M_diff.l1       -0.009948   0.502216  -0.020 0.984300    
Dep_Total_yoy_diff.l1   0.786042   0.208278   3.774 0.000549 ***
Desemprego_yoy_diff.l1 -0.174621   0.082280  -2.122 0.040391 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 3.747 on 38 degrees of freedom
Multiple R-Squared: 0.4627, Adjusted R-squared: 0.392 
F-statistic: 6.544 on 5 and 38 DF,  p-value: 0.000176 


Estimation results for equation Desemprego_yoy_diff: 
==================================================== 
Desemprego_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 

                       Estimate Std. Error t value Pr(&gt;|t|)    
PIB_yoy.l1              0.05815    0.35254   0.165 0.869852    
Selic_diff.l1          -0.93683    8.08365  -0.116 0.908348    
IPCA_12M_diff.l1       -0.65666    0.82743  -0.794 0.432346    
Dep_Total_yoy_diff.l1   0.08266    0.34315   0.241 0.810936    
Desemprego_yoy_diff.l1  0.56231    0.13556   4.148 0.000182 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 6.174 on 38 degrees of freedom
Multiple R-Squared: 0.3346, Adjusted R-squared: 0.247 
F-statistic: 3.821 on 5 and 38 DF,  p-value: 0.006679 



Covariance matrix of residuals:
                      PIB_yoy Selic_diff IPCA_12M_diff Dep_Total_yoy_diff
PIB_yoy              6.271157   0.107325     -0.003535            -5.3965
Selic_diff           0.107325   0.006565      0.018040            -0.1885
IPCA_12M_diff       -0.003535   0.018040      1.768097            -1.6342
Dep_Total_yoy_diff  -5.396490  -0.188480     -1.634180            13.9092
Desemprego_yoy_diff -0.948721   0.025329      1.641303             0.1417
                    Desemprego_yoy_diff
PIB_yoy                        -0.94872
Selic_diff                      0.02533
IPCA_12M_diff                   1.64130
Dep_Total_yoy_diff              0.14169
Desemprego_yoy_diff            37.77198

Correlation matrix of residuals:
                      PIB_yoy Selic_diff IPCA_12M_diff Dep_Total_yoy_diff
PIB_yoy              1.000000    0.52895     -0.001062          -0.577812
Selic_diff           0.528953    1.00000      0.167449          -0.623738
IPCA_12M_diff       -0.001062    0.16745      1.000000          -0.329530
Dep_Total_yoy_diff  -0.577812   -0.62374     -0.329530           1.000000
Desemprego_yoy_diff -0.061642    0.05087      0.200840           0.006182
                    Desemprego_yoy_diff
PIB_yoy                       -0.061642
Selic_diff                     0.050866
IPCA_12M_diff                  0.200840
Dep_Total_yoy_diff             0.006182
Desemprego_yoy_diff            1.000000</code></pre>
</div>
</div>
<ul>
<li><strong>Estimando um modelo VAR(2)</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>var_2lags <span class="ot">&lt;-</span> <span class="fu">VAR</span>(data_macro_filtered_numeric, <span class="at">p =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"none"</span>)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(var_2lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
VAR Estimation Results:
========================= 
Endogenous variables: PIB_yoy, Selic_diff, IPCA_12M_diff, Dep_Total_yoy_diff, Desemprego_yoy_diff 
Deterministic variables: none 
Sample size: 42 
Log Likelihood: -315.554 
Roots of the characteristic polynomial:
0.8128 0.8128 0.6689 0.6689 0.564 0.564 0.5339 0.5339 0.3048 0.1483
Call:
VAR(y = data_macro_filtered_numeric, p = 2, type = "none")


Estimation results for equation PIB_yoy: 
======================================== 
PIB_yoy = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 

                         Estimate Std. Error t value Pr(&gt;|t|)   
PIB_yoy.l1               0.380553   0.202598   1.878  0.06947 . 
Selic_diff.l1          -10.306668   6.417584  -1.606  0.11810   
IPCA_12M_diff.l1        -0.228722   0.330769  -0.691  0.49425   
Dep_Total_yoy_diff.l1   -0.532331   0.155248  -3.429  0.00169 **
Desemprego_yoy_diff.l1   0.141119   0.066761   2.114  0.04242 * 
PIB_yoy.l2               0.183917   0.189682   0.970  0.33952   
Selic_diff.l2           10.098308   5.237650   1.928  0.06277 . 
IPCA_12M_diff.l2        -0.133004   0.359546  -0.370  0.71388   
Dep_Total_yoy_diff.l2    0.388129   0.159569   2.432  0.02077 * 
Desemprego_yoy_diff.l2   0.004853   0.076115   0.064  0.94956   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 2.427 on 32 degrees of freedom
Multiple R-Squared: 0.6429, Adjusted R-squared: 0.5312 
F-statistic:  5.76 on 10 and 32 DF,  p-value: 6.63e-05 


Estimation results for equation Selic_diff: 
=========================================== 
Selic_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 

                         Estimate Std. Error t value Pr(&gt;|t|)   
PIB_yoy.l1             -0.0124729  0.0068626  -1.818  0.07851 . 
Selic_diff.l1           0.5545380  0.2173843   2.551  0.01573 * 
IPCA_12M_diff.l1        0.0169530  0.0112042   1.513  0.14007   
Dep_Total_yoy_diff.l1  -0.0180258  0.0052587  -3.428  0.00169 **
Desemprego_yoy_diff.l1  0.0052571  0.0022614   2.325  0.02659 * 
PIB_yoy.l2              0.0079697  0.0064252   1.240  0.22385   
Selic_diff.l2           0.0930502  0.1774161   0.524  0.60356   
IPCA_12M_diff.l2        0.0107103  0.0121790   0.879  0.38574   
Dep_Total_yoy_diff.l2   0.0121886  0.0054051   2.255  0.03111 * 
Desemprego_yoy_diff.l2  0.0008058  0.0025783   0.313  0.75667   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 0.0822 on 32 degrees of freedom
Multiple R-Squared: 0.8305, Adjusted R-squared: 0.7775 
F-statistic: 15.68 on 10 and 32 DF,  p-value: 1.122e-09 


Estimation results for equation IPCA_12M_diff: 
============================================== 
IPCA_12M_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 

                       Estimate Std. Error t value Pr(&gt;|t|)  
PIB_yoy.l1             -0.20379    0.10420  -1.956   0.0593 .
Selic_diff.l1           7.58983    3.30057   2.300   0.0281 *
IPCA_12M_diff.l1        0.06341    0.17011   0.373   0.7118  
Dep_Total_yoy_diff.l1  -0.10174    0.07984  -1.274   0.2118  
Desemprego_yoy_diff.l1  0.03098    0.03434   0.902   0.3737  
PIB_yoy.l2              0.21936    0.09755   2.249   0.0316 *
Selic_diff.l2          -7.16712    2.69373  -2.661   0.0121 *
IPCA_12M_diff.l2       -0.04613    0.18491  -0.249   0.8046  
Dep_Total_yoy_diff.l2   0.08979    0.08207   1.094   0.2821  
Desemprego_yoy_diff.l2 -0.06110    0.03915  -1.561   0.1284  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 1.248 on 32 degrees of freedom
Multiple R-Squared: 0.3559, Adjusted R-squared: 0.1546 
F-statistic: 1.768 on 10 and 32 DF,  p-value: 0.1079 


Estimation results for equation Dep_Total_yoy_diff: 
=================================================== 
Dep_Total_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 

                        Estimate Std. Error t value Pr(&gt;|t|)    
PIB_yoy.l1               0.48612    0.30181   1.611 0.117069    
Selic_diff.l1          -11.91690    9.56029  -1.246 0.221629    
IPCA_12M_diff.l1        -0.03071    0.49275  -0.062 0.950688    
Dep_Total_yoy_diff.l1    0.90510    0.23127   3.914 0.000446 ***
Desemprego_yoy_diff.l1  -0.14545    0.09945  -1.463 0.153349    
PIB_yoy.l2              -0.46409    0.28257  -1.642 0.110302    
Selic_diff.l2            6.24686    7.80254   0.801 0.429257    
IPCA_12M_diff.l2        -0.11782    0.53562  -0.220 0.827288    
Dep_Total_yoy_diff.l2   -0.60325    0.23771  -2.538 0.016226 *  
Desemprego_yoy_diff.l2   0.10127    0.11339   0.893 0.378465    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 3.615 on 32 degrees of freedom
Multiple R-Squared: 0.5782, Adjusted R-squared: 0.4464 
F-statistic: 4.387 on 10 and 32 DF,  p-value: 0.0006492 


Estimation results for equation Desemprego_yoy_diff: 
==================================================== 
Desemprego_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 

                       Estimate Std. Error t value Pr(&gt;|t|)    
PIB_yoy.l1               0.2496     0.4952   0.504 0.617719    
Selic_diff.l1           19.6239    15.6866   1.251 0.220005    
IPCA_12M_diff.l1        -0.9723     0.8085  -1.203 0.237974    
Dep_Total_yoy_diff.l1    0.4859     0.3795   1.280 0.209614    
Desemprego_yoy_diff.l1   0.6547     0.1632   4.012 0.000339 ***
PIB_yoy.l2              -0.3357     0.4636  -0.724 0.474362    
Selic_diff.l2          -24.2735    12.8025  -1.896 0.067021 .  
IPCA_12M_diff.l2         0.2397     0.8788   0.273 0.786791    
Dep_Total_yoy_diff.l2   -0.4822     0.3900  -1.236 0.225395    
Desemprego_yoy_diff.l2  -0.2133     0.1860  -1.147 0.260074    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 5.931 on 32 degrees of freedom
Multiple R-Squared: 0.4539, Adjusted R-squared: 0.2832 
F-statistic:  2.66 on 10 and 32 DF,  p-value: 0.01734 



Covariance matrix of residuals:
                    PIB_yoy Selic_diff IPCA_12M_diff Dep_Total_yoy_diff
PIB_yoy              5.7014   0.100743       0.22042            -5.5542
Selic_diff           0.1007   0.006661       0.01769            -0.1778
IPCA_12M_diff        0.2204   0.017685       1.55588            -1.0025
Dep_Total_yoy_diff  -5.5542  -0.177757      -1.00250            13.0480
Desemprego_yoy_diff  2.4520   0.078148       1.01845             0.2379
                    Desemprego_yoy_diff
PIB_yoy                         2.45203
Selic_diff                      0.07815
IPCA_12M_diff                   1.01845
Dep_Total_yoy_diff              0.23785
Desemprego_yoy_diff            34.94159

Correlation matrix of residuals:
                     PIB_yoy Selic_diff IPCA_12M_diff Dep_Total_yoy_diff
PIB_yoy              1.00000     0.5169       0.07401           -0.64396
Selic_diff           0.51695     1.0000       0.17372           -0.60294
IPCA_12M_diff        0.07401     0.1737       1.00000           -0.22250
Dep_Total_yoy_diff  -0.64396    -0.6029      -0.22250            1.00000
Desemprego_yoy_diff  0.17373     0.1620       0.13813            0.01114
                    Desemprego_yoy_diff
PIB_yoy                         0.17373
Selic_diff                      0.16198
IPCA_12M_diff                   0.13813
Dep_Total_yoy_diff              0.01114
Desemprego_yoy_diff             1.00000</code></pre>
</div>
</div>
<ul>
<li><strong>Estimando um modelo VAR(5)</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>var_5lags <span class="ot">&lt;-</span> <span class="fu">VAR</span>(data_macro_filtered_numeric, <span class="at">p =</span> <span class="dv">5</span>, <span class="at">type =</span> <span class="st">"none"</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(var_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
VAR Estimation Results:
========================= 
Endogenous variables: PIB_yoy, Selic_diff, IPCA_12M_diff, Dep_Total_yoy_diff, Desemprego_yoy_diff 
Deterministic variables: none 
Sample size: 39 
Log Likelihood: -148.483 
Roots of the characteristic polynomial:
0.9948 0.9948 0.9735 0.9735 0.963 0.963 0.9493 0.9493 0.9389 0.9389 0.9326 0.9326 0.9107 0.9107 0.9095 0.9095 0.8876 0.8876 0.8227 0.8227 0.8117 0.8117 0.7579 0.7579 0.09342
Call:
VAR(y = data_macro_filtered_numeric, p = 5, type = "none")


Estimation results for equation PIB_yoy: 
======================================== 
PIB_yoy = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 + PIB_yoy.l3 + Selic_diff.l3 + IPCA_12M_diff.l3 + Dep_Total_yoy_diff.l3 + Desemprego_yoy_diff.l3 + PIB_yoy.l4 + Selic_diff.l4 + IPCA_12M_diff.l4 + Dep_Total_yoy_diff.l4 + Desemprego_yoy_diff.l4 + PIB_yoy.l5 + Selic_diff.l5 + IPCA_12M_diff.l5 + Dep_Total_yoy_diff.l5 + Desemprego_yoy_diff.l5 

                        Estimate Std. Error t value Pr(&gt;|t|)  
PIB_yoy.l1               0.37774    0.32713   1.155   0.2675  
Selic_diff.l1          -10.54255    9.90251  -1.065   0.3051  
IPCA_12M_diff.l1        -1.32512    0.77492  -1.710   0.1093  
Dep_Total_yoy_diff.l1   -0.58399    0.32112  -1.819   0.0904 .
Desemprego_yoy_diff.l1   0.18089    0.07091   2.551   0.0231 *
PIB_yoy.l2               0.02178    0.36523   0.060   0.9533  
Selic_diff.l2           23.94322    9.34037   2.563   0.0225 *
IPCA_12M_diff.l2        -0.47546    0.53756  -0.884   0.3914  
Dep_Total_yoy_diff.l2    0.21824    0.31642   0.690   0.5016  
Desemprego_yoy_diff.l2  -0.04131    0.10806  -0.382   0.7080  
PIB_yoy.l3               0.45710    0.32637   1.401   0.1831  
Selic_diff.l3            1.55346   11.18531   0.139   0.8915  
IPCA_12M_diff.l3        -0.25915    0.44058  -0.588   0.5658  
Dep_Total_yoy_diff.l3    0.41910    0.21735   1.928   0.0744 .
Desemprego_yoy_diff.l3  -0.10560    0.13084  -0.807   0.4331  
PIB_yoy.l4              -0.07661    0.29096  -0.263   0.7961  
Selic_diff.l4           -6.64456   11.05055  -0.601   0.5573  
IPCA_12M_diff.l4         0.58818    0.43484   1.353   0.1976  
Dep_Total_yoy_diff.l4    0.27990    0.27947   1.002   0.3336  
Desemprego_yoy_diff.l4   0.03113    0.11680   0.267   0.7937  
PIB_yoy.l5               0.22844    0.27139   0.842   0.4141  
Selic_diff.l5           -9.43074    8.92242  -1.057   0.3084  
IPCA_12M_diff.l5        -0.34167    0.76418  -0.447   0.6616  
Dep_Total_yoy_diff.l5   -0.39388    0.26661  -1.477   0.1617  
Desemprego_yoy_diff.l5  -0.09135    0.13107  -0.697   0.4972  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 1.963 on 14 degrees of freedom
Multiple R-Squared: 0.894,  Adjusted R-squared: 0.7046 
F-statistic: 4.722 on 25 and 14 DF,  p-value: 0.001997 


Estimation results for equation Selic_diff: 
=========================================== 
Selic_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 + PIB_yoy.l3 + Selic_diff.l3 + IPCA_12M_diff.l3 + Dep_Total_yoy_diff.l3 + Desemprego_yoy_diff.l3 + PIB_yoy.l4 + Selic_diff.l4 + IPCA_12M_diff.l4 + Dep_Total_yoy_diff.l4 + Desemprego_yoy_diff.l4 + PIB_yoy.l5 + Selic_diff.l5 + IPCA_12M_diff.l5 + Dep_Total_yoy_diff.l5 + Desemprego_yoy_diff.l5 

                         Estimate Std. Error t value Pr(&gt;|t|)   
PIB_yoy.l1             -0.0306724  0.0109098  -2.811  0.01386 * 
Selic_diff.l1          -0.0850410  0.3302449  -0.258  0.80053   
IPCA_12M_diff.l1        0.0146670  0.0258434   0.568  0.57934   
Dep_Total_yoy_diff.l1  -0.0322047  0.0107091  -3.007  0.00942 **
Desemprego_yoy_diff.l1  0.0032689  0.0023647   1.382  0.18852   
PIB_yoy.l2              0.0128915  0.0121804   1.058  0.30780   
Selic_diff.l2          -0.0695004  0.3114978  -0.223  0.82667   
IPCA_12M_diff.l2       -0.0084346  0.0179275  -0.470  0.64525   
Dep_Total_yoy_diff.l2  -0.0019861  0.0105526  -0.188  0.85341   
Desemprego_yoy_diff.l2  0.0076960  0.0036038   2.136  0.05087 . 
PIB_yoy.l3              0.0178433  0.0108843   1.639  0.12341   
Selic_diff.l3           0.4780226  0.3730259   1.281  0.22085   
IPCA_12M_diff.l3        0.0052372  0.0146930   0.356  0.72682   
Dep_Total_yoy_diff.l3   0.0095920  0.0072486   1.323  0.20695   
Desemprego_yoy_diff.l3 -0.0002474  0.0043636  -0.057  0.95558   
PIB_yoy.l4              0.0132164  0.0097034   1.362  0.19470   
Selic_diff.l4           0.5409355  0.3685317   1.468  0.16426   
IPCA_12M_diff.l4        0.0484476  0.0145017   3.341  0.00485 **
Dep_Total_yoy_diff.l4   0.0328574  0.0093203   3.525  0.00336 **
Desemprego_yoy_diff.l4 -0.0011102  0.0038952  -0.285  0.77980   
PIB_yoy.l5             -0.0035004  0.0090509  -0.387  0.70476   
Selic_diff.l5          -0.4149706  0.2975593  -1.395  0.18488   
IPCA_12M_diff.l5        0.0372011  0.0254851   1.460  0.16644   
Dep_Total_yoy_diff.l5  -0.0005514  0.0088912  -0.062  0.95143   
Desemprego_yoy_diff.l5 -0.0085718  0.0043710  -1.961  0.07008 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 0.06547 on 14 degrees of freedom
Multiple R-Squared: 0.9523, Adjusted R-squared: 0.8671 
F-statistic: 11.18 on 25 and 14 DF,  p-value: 1.384e-05 


Estimation results for equation IPCA_12M_diff: 
============================================== 
IPCA_12M_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 + PIB_yoy.l3 + Selic_diff.l3 + IPCA_12M_diff.l3 + Dep_Total_yoy_diff.l3 + Desemprego_yoy_diff.l3 + PIB_yoy.l4 + Selic_diff.l4 + IPCA_12M_diff.l4 + Dep_Total_yoy_diff.l4 + Desemprego_yoy_diff.l4 + PIB_yoy.l5 + Selic_diff.l5 + IPCA_12M_diff.l5 + Dep_Total_yoy_diff.l5 + Desemprego_yoy_diff.l5 

                        Estimate Std. Error t value Pr(&gt;|t|)  
PIB_yoy.l1             -0.193544   0.154649  -1.251   0.2313  
Selic_diff.l1           1.944178   4.681333   0.415   0.6842  
IPCA_12M_diff.l1        0.123372   0.366339   0.337   0.7413  
Dep_Total_yoy_diff.l1  -0.138571   0.151806  -0.913   0.3768  
Desemprego_yoy_diff.l1  0.018793   0.033521   0.561   0.5839  
PIB_yoy.l2             -0.109562   0.172661  -0.635   0.5360  
Selic_diff.l2          -3.474331   4.415585  -0.787   0.4445  
IPCA_12M_diff.l2       -0.315777   0.254128  -1.243   0.2344  
Dep_Total_yoy_diff.l2   0.001424   0.149587   0.010   0.9925  
Desemprego_yoy_diff.l2 -0.041927   0.051085  -0.821   0.4256  
PIB_yoy.l3              0.193196   0.154289   1.252   0.2310  
Selic_diff.l3          -1.025907   5.287767  -0.194   0.8490  
IPCA_12M_diff.l3        0.294824   0.208279   1.416   0.1788  
Dep_Total_yoy_diff.l3  -0.048108   0.102752  -0.468   0.6469  
Desemprego_yoy_diff.l3  0.052165   0.061856   0.843   0.4132  
PIB_yoy.l4              0.224854   0.137550   1.635   0.1244  
Selic_diff.l4           2.661493   5.224060   0.509   0.6184  
IPCA_12M_diff.l4       -0.376590   0.205566  -1.832   0.0883 .
Dep_Total_yoy_diff.l4   0.114414   0.132118   0.866   0.4011  
Desemprego_yoy_diff.l4 -0.031824   0.055216  -0.576   0.5735  
PIB_yoy.l5              0.012006   0.128299   0.094   0.9268  
Selic_diff.l5          -2.779697   4.218003  -0.659   0.5206  
IPCA_12M_diff.l5        0.469789   0.361260   1.300   0.2145  
Dep_Total_yoy_diff.l5   0.146613   0.126036   1.163   0.2642  
Desemprego_yoy_diff.l5 -0.041394   0.061961  -0.668   0.5149  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 0.9281 on 14 degrees of freedom
Multiple R-Squared: 0.8437, Adjusted R-squared: 0.5647 
F-statistic: 3.024 on 25 and 14 DF,  p-value: 0.0173 


Estimation results for equation Dep_Total_yoy_diff: 
=================================================== 
Dep_Total_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 + PIB_yoy.l3 + Selic_diff.l3 + IPCA_12M_diff.l3 + Dep_Total_yoy_diff.l3 + Desemprego_yoy_diff.l3 + PIB_yoy.l4 + Selic_diff.l4 + IPCA_12M_diff.l4 + Dep_Total_yoy_diff.l4 + Desemprego_yoy_diff.l4 + PIB_yoy.l5 + Selic_diff.l5 + IPCA_12M_diff.l5 + Dep_Total_yoy_diff.l5 + Desemprego_yoy_diff.l5 

                         Estimate Std. Error t value Pr(&gt;|t|)  
PIB_yoy.l1               0.614865   0.447166   1.375   0.1907  
Selic_diff.l1           -3.922029  13.535992  -0.290   0.7763  
IPCA_12M_diff.l1        -0.168279   1.059263  -0.159   0.8760  
Dep_Total_yoy_diff.l1    0.690489   0.438943   1.573   0.1380  
Desemprego_yoy_diff.l1  -0.171768   0.096925  -1.772   0.0981 .
PIB_yoy.l2               0.035242   0.499247   0.071   0.9447  
Selic_diff.l2           -0.451442  12.767587  -0.035   0.9723  
IPCA_12M_diff.l2         0.269889   0.734806   0.367   0.7189  
Dep_Total_yoy_diff.l2   -0.310029   0.432528  -0.717   0.4853  
Desemprego_yoy_diff.l2   0.126057   0.147711   0.853   0.4078  
PIB_yoy.l3              -0.165683   0.446124  -0.371   0.7159  
Selic_diff.l3           -1.792296  15.289485  -0.117   0.9083  
IPCA_12M_diff.l3         0.455217   0.602235   0.756   0.4623  
Dep_Total_yoy_diff.l3    0.013249   0.297106   0.045   0.9651  
Desemprego_yoy_diff.l3  -0.228870   0.178855  -1.280   0.2215  
PIB_yoy.l4              -0.180729   0.397722  -0.454   0.6565  
Selic_diff.l4          -10.433410  15.105278  -0.691   0.5010  
IPCA_12M_diff.l4        -0.428392   0.594391  -0.721   0.4829  
Dep_Total_yoy_diff.l4   -0.770234   0.382016  -2.016   0.0634 .
Desemprego_yoy_diff.l4  -0.075713   0.159657  -0.474   0.6427  
PIB_yoy.l5              -0.309734   0.370976  -0.835   0.4178  
Selic_diff.l5           10.371405  12.196283   0.850   0.4094  
IPCA_12M_diff.l5        -0.687658   1.044578  -0.658   0.5210  
Dep_Total_yoy_diff.l5   -0.059056   0.364430  -0.162   0.8736  
Desemprego_yoy_diff.l5  -0.005524   0.179158  -0.031   0.9758  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 2.684 on 14 degrees of freedom
Multiple R-Squared: 0.8975, Adjusted R-squared: 0.7146 
F-statistic: 4.905 on 25 and 14 DF,  p-value: 0.001634 


Estimation results for equation Desemprego_yoy_diff: 
==================================================== 
Desemprego_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 + PIB_yoy.l3 + Selic_diff.l3 + IPCA_12M_diff.l3 + Dep_Total_yoy_diff.l3 + Desemprego_yoy_diff.l3 + PIB_yoy.l4 + Selic_diff.l4 + IPCA_12M_diff.l4 + Dep_Total_yoy_diff.l4 + Desemprego_yoy_diff.l4 + PIB_yoy.l5 + Selic_diff.l5 + IPCA_12M_diff.l5 + Dep_Total_yoy_diff.l5 + Desemprego_yoy_diff.l5 

                        Estimate Std. Error t value Pr(&gt;|t|)   
PIB_yoy.l1              -0.56310    0.93582  -0.602  0.55698   
Selic_diff.l1           17.11846   28.32777   0.604  0.55531   
IPCA_12M_diff.l1        -0.51983    2.21680  -0.234  0.81799   
Dep_Total_yoy_diff.l1   -0.41258    0.91861  -0.449  0.66021   
Desemprego_yoy_diff.l1   0.67956    0.20284   3.350  0.00476 **
PIB_yoy.l2               1.80092    1.04481   1.724  0.10677   
Selic_diff.l2          -35.26028   26.71967  -1.320  0.20813   
IPCA_12M_diff.l2         2.02081    1.53778   1.314  0.20994   
Dep_Total_yoy_diff.l2    0.54704    0.90518   0.604  0.55529   
Desemprego_yoy_diff.l2  -0.08008    0.30913  -0.259  0.79936   
PIB_yoy.l3              -0.09705    0.93364  -0.104  0.91868   
Selic_diff.l3           34.13201   31.99744   1.067  0.30415   
IPCA_12M_diff.l3         1.95979    1.26034   1.555  0.14226   
Dep_Total_yoy_diff.l3    0.32975    0.62177   0.530  0.60419   
Desemprego_yoy_diff.l3  -0.28560    0.37430  -0.763  0.45811   
PIB_yoy.l4               1.33252    0.83234   1.601  0.13171   
Selic_diff.l4          -30.38973   31.61193  -0.961  0.35269   
IPCA_12M_diff.l4         0.10347    1.24393   0.083  0.93489   
Dep_Total_yoy_diff.l4    1.10487    0.79947   1.382  0.18863   
Desemprego_yoy_diff.l4  -0.29808    0.33413  -0.892  0.38741   
PIB_yoy.l5              -2.85233    0.77637  -3.674  0.00250 **
Selic_diff.l5           22.26192   25.52406   0.872  0.39781   
IPCA_12M_diff.l5        -1.60849    2.18606  -0.736  0.47401   
Dep_Total_yoy_diff.l5   -1.73703    0.76267  -2.278  0.03897 * 
Desemprego_yoy_diff.l5   0.22954    0.37494   0.612  0.55022   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Residual standard error: 5.616 on 14 degrees of freedom
Multiple R-Squared: 0.785,  Adjusted R-squared: 0.4011 
F-statistic: 2.045 on 25 and 14 DF,  p-value: 0.08233 



Covariance matrix of residuals:
                    PIB_yoy Selic_diff IPCA_12M_diff Dep_Total_yoy_diff
PIB_yoy              3.8265   0.017705       0.62868            -3.5824
Selic_diff           0.0177   0.004221       0.04412            -0.1108
IPCA_12M_diff        0.6287   0.044120       0.81872            -1.6159
Dep_Total_yoy_diff  -3.5824  -0.110760      -1.61594             7.2015
Desemprego_yoy_diff  2.5658   0.096172       1.83729            -3.9801
                    Desemprego_yoy_diff
PIB_yoy                         2.56577
Selic_diff                      0.09617
IPCA_12M_diff                   1.83729
Dep_Total_yoy_diff             -3.98014
Desemprego_yoy_diff            30.61309

Correlation matrix of residuals:
                    PIB_yoy Selic_diff IPCA_12M_diff Dep_Total_yoy_diff
PIB_yoy              1.0000     0.1393        0.3552            -0.6824
Selic_diff           0.1393     1.0000        0.7505            -0.6352
IPCA_12M_diff        0.3552     0.7505        1.0000            -0.6655
Dep_Total_yoy_diff  -0.6824    -0.6352       -0.6655             1.0000
Desemprego_yoy_diff  0.2371     0.2675        0.3670            -0.2681
                    Desemprego_yoy_diff
PIB_yoy                          0.2371
Selic_diff                       0.2675
IPCA_12M_diff                    0.3670
Dep_Total_yoy_diff              -0.2681
Desemprego_yoy_diff              1.0000</code></pre>
</div>
</div>
<p><strong>A equação considerando a taxa selic diferenciada como variável objetivo se apresentou a mais representativa do ponto de vista coeficientes com maior peso no modelo.</strong></p>
<pre><code>Dep_Total_yoy_diff.l1  -0.013224   0.004603  -2.873 0.006621 **  Desemprego_yoy_diff.l1  0.006709   0.001818   3.690 0.000701 ***</code></pre>
<pre><code>Estimation results for equation Selic_diff:  ===========================================  Selic_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 </code></pre>
<p><strong>Porém, conforme solicita o enunciado, o modelo que estamos procurando estimar é um que permita realizarmos as previsões de depósitos bancários contra alguns indicadores macro econômicos:</strong></p>
<p><strong>Resultados dos modelos estimados considerando 1, 2 e 5 lags:</strong></p>
<p><strong>Modelo estimado para 1 lag</strong></p>
<pre><code>Estimation results for equation Dep_Total_yoy_diff:  ===================================================  
Dep_Total_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1                                                      Estimate   Std. Error t value Pr(&gt;|t|)     
PIB_yoy.l1              0.302796   0.213980   1.415 0.165191    
Selic_diff.l1           2.064378   4.906456   0.421 0.676310     IPCA_12M_diff.l1       -0.009948   0.502216  -0.020 0.984300     Dep_Total_yoy_diff.l1   0.786042   0.208278   3.774 0.000549 *** Desemprego_yoy_diff.l1 -0.174621   0.082280  -2.122 0.040391 *   
--- Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1 </code></pre>
<p><strong>Modelo estimado para 2 lags</strong></p>
<pre><code>Estimation results for equation Dep_Total_yoy_diff:  =================================================== 
Dep_Total_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2

Estimate Std. Error t value Pr(&gt;|t|)     
PIB_yoy.l1               0.48612    0.30181   1.611 0.117069     
Selic_diff.l1          -11.91690    9.56029  -1.246 0.221629     IPCA_12M_diff.l1        -0.03071    0.49275  -0.062 0.950688     Dep_Total_yoy_diff.l1    0.90510    0.23127   3.914 0.000446 *** Desemprego_yoy_diff.l1  -0.14545    0.09945  -1.463 0.153349     
PIB_yoy.l2              -0.46409    0.28257  -1.642 0.110302     
Selic_diff.l2            6.24686    7.80254   0.801 0.429257     IPCA_12M_diff.l2        -0.11782    0.53562  -0.220 0.827288     Dep_Total_yoy_diff.l2   -0.60325    0.23771  -2.538 0.016226 *   Desemprego_yoy_diff.l2   0.10127    0.11339   0.893 0.378465     
--- Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1 </code></pre>
<p><strong>Modelo estimado com 5 lags</strong></p>
<pre><code>Estimation results for equation Dep_Total_yoy_diff:  ===================================================  
Dep_Total_yoy_diff = PIB_yoy.l1 + Selic_diff.l1 + IPCA_12M_diff.l1 + Dep_Total_yoy_diff.l1 + Desemprego_yoy_diff.l1 + PIB_yoy.l2 + Selic_diff.l2 + IPCA_12M_diff.l2 + Dep_Total_yoy_diff.l2 + Desemprego_yoy_diff.l2 + PIB_yoy.l3 + Selic_diff.l3 + IPCA_12M_diff.l3 + Dep_Total_yoy_diff.l3 + Desemprego_yoy_diff.l3 + PIB_yoy.l4 + Selic_diff.l4 + IPCA_12M_diff.l4 + Dep_Total_yoy_diff.l4 + Desemprego_yoy_diff.l4 + PIB_yoy.l5 + Selic_diff.l5 + IPCA_12M_diff.l5 + Dep_Total_yoy_diff.l5 + Desemprego_yoy_diff.l5                            
                         Estimate   Std. Error t value Pr(&gt;|t|)   
PIB_yoy.l1               0.614865   0.447166   1.375   0.1907   
Selic_diff.l1           -3.922029  13.535992  -0.290   0.7763   IPCA_12M_diff.l1        -0.168279   1.059263  -0.159   0.8760   Dep_Total_yoy_diff.l1    0.690489   0.438943   1.573   0.1380   Desemprego_yoy_diff.l1  -0.171768   0.096925  -1.772   0.0981 . 
PIB_yoy.l2               0.035242   0.499247   0.071   0.9447   
Selic_diff.l2           -0.451442  12.767587  -0.035   0.9723   IPCA_12M_diff.l2         0.269889   0.734806   0.367   0.7189   Dep_Total_yoy_diff.l2   -0.310029   0.432528  -0.717   0.4853   Desemprego_yoy_diff.l2   0.126057   0.147711   0.853   0.4078   
PIB_yoy.l3              -0.165683   0.446124  -0.371   0.7159   
Selic_diff.l3           -1.792296  15.289485  -0.117   0.9083   IPCA_12M_diff.l3         0.455217   0.602235   0.756   0.4623   Dep_Total_yoy_diff.l3    0.013249   0.297106   0.045   0.9651   Desemprego_yoy_diff.l3  -0.228870   0.178855  -1.280   0.2215   
PIB_yoy.l4              -0.180729   0.397722  -0.454   0.6565   
Selic_diff.l4          -10.433410  15.105278  -0.691   0.5010   IPCA_12M_diff.l4        -0.428392   0.594391  -0.721   0.4829   Dep_Total_yoy_diff.l4   -0.770234   0.382016  -2.016   0.0634 . Desemprego_yoy_diff.l4  -0.075713   0.159657  -0.474   0.6427   
PIB_yoy.l5              -0.309734   0.370976  -0.835   0.4178   
Selic_diff.l5           10.371405  12.196283   0.850   0.4094   IPCA_12M_diff.l5        -0.687658   1.044578  -0.658   0.5210   Dep_Total_yoy_diff.l5   -0.059056   0.364430  -0.162   0.8736   Desemprego_yoy_diff.l5  -0.005524   0.179158  -0.031   0.9758   
--- Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1 </code></pre>
<p>Como podemos verificar, os modelos mais parcimoniosos tendem a responder melhor nossas perguntas, demonstrando que os coeficientes relacionados aos lags anteriores dos depósitos bem como o desemprego assumem relevância estatística bem como influência no valor presente da série objetivo.</p>
<p>De qualquer forma, para que possamos estimar um modelo mais robusto, cabe explorar mais variáveis macro-econômicas para identificar coeficientes estimadores melhores para explicar a série objetivo.</p>
</section>
<section id="c.-estime-o-modelo-var-com-a-ordem-escolhida-utilizando-a-função-var-do-pacote-vars." class="level3">
<h3 class="anchored" data-anchor-id="c.-estime-o-modelo-var-com-a-ordem-escolhida-utilizando-a-função-var-do-pacote-vars.">c.&nbsp;Estime o modelo VAR com a ordem escolhida utilizando a função VAR() do pacote vars.</h3>
<ul>
<li><p>Analise a estabilidade do modelo verificando as raízes dos polinômios com a função roots(), garantindo que estejam dentro do círculo unitário.</p></li>
<li><p>Realize o diagnóstico dos resíduos para verificar a presença de autocorrelação (serial.test()), normalidade (normality.test()) e heterocedasticidade (arch.test()).</p></li>
<li><p>Apresente e discuta os resultados, incluindo a interpretação dos coeficientes estimados.</p></li>
</ul>
<p><strong>Vamos executar os testes para avaliacao da estabilidade dos modelos</strong></p>
<p><strong>Verificando as raizes dos polinomios</strong></p>
<p><strong>Raízes dos polinômios do modelo com 1 lag:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>roots_1lag <span class="ot">&lt;-</span> <span class="fu">roots</span>(var_1lag)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(roots_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7683823 0.6196473 0.5568246 0.5568246 0.1026215</code></pre>
</div>
</div>
<p><strong>Raízes dos polinômios do modelo com 2 lags:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>roots_2lags <span class="ot">&lt;-</span> <span class="fu">roots</span>(var_2lags)</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(roots_2lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.8127935 0.8127935 0.6689272 0.6689272 0.5640152 0.5640152 0.5339252
 [8] 0.5339252 0.3048373 0.1483135</code></pre>
</div>
</div>
<p><strong>Raízes dos polinômios do modelo com 5 lags:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>roots_5lags <span class="ot">&lt;-</span> <span class="fu">roots</span>(var_5lags)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(roots_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.99484057 0.99484057 0.97345941 0.97345941 0.96302315 0.96302315
 [7] 0.94928794 0.94928794 0.93887014 0.93887014 0.93264249 0.93264249
[13] 0.91074776 0.91074776 0.90948808 0.90948808 0.88761308 0.88761308
[19] 0.82274178 0.82274178 0.81168118 0.81168118 0.75785571 0.75785571
[25] 0.09341832</code></pre>
</div>
</div>
<p>Analisando as raizes podemos verificar que todas possuem valores menores que 1, portanto, ambos os modelos sao estaveis.</p>
<p><strong>Vamos realizar o os diagnosticos nos residuos dos modelos.</strong></p>
<ul>
<li><strong>Realizando o teste Portmanteau no modelo com 1 lag</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>serial_test_1lag <span class="ot">&lt;-</span> <span class="fu">serial.test</span>(var_1lag , <span class="at">lags.pt =</span> <span class="dv">25</span>, <span class="at">type =</span> <span class="st">"PT.asymptotic"</span>)</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(serial_test_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Portmanteau Test (asymptotic)

data:  Residuals of VAR object var_1lag
Chi-squared = 485.11, df = 600, p-value = 0.9998</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$serial

    Portmanteau Test (asymptotic)

data:  Residuals of VAR object var_1lag
Chi-squared = 485.11, df = 600, p-value = 0.9998</code></pre>
</div>
</div>
<ul>
<li><p>Realizando o teste Portmanteau no modelo com 2 lags</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>serial_test_2lags <span class="ot">&lt;-</span> <span class="fu">serial.test</span>(var_2lags , <span class="at">lags.pt =</span> <span class="dv">25</span>, <span class="at">type =</span> <span class="st">"PT.asymptotic"</span>)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(serial_test_2lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Portmanteau Test (asymptotic)

data:  Residuals of VAR object var_2lags
Chi-squared = 459.15, df = 575, p-value = 0.9999</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$serial

    Portmanteau Test (asymptotic)

data:  Residuals of VAR object var_2lags
Chi-squared = 459.15, df = 575, p-value = 0.9999</code></pre>
</div>
</div></li>
<li><p><strong>Realizando o teste Portmanteau no modelo com 5 lags</strong></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>serial_test_5lags <span class="ot">&lt;-</span> <span class="fu">serial.test</span>(var_5lags , <span class="at">lags.pt =</span> <span class="dv">25</span>, <span class="at">type =</span> <span class="st">"PT.asymptotic"</span>)</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(serial_test_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Portmanteau Test (asymptotic)

data:  Residuals of VAR object var_5lags
Chi-squared = 469.98, df = 500, p-value = 0.8284</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$serial

    Portmanteau Test (asymptotic)

data:  Residuals of VAR object var_5lags
Chi-squared = 469.98, df = 500, p-value = 0.8284</code></pre>
</div>
</div>
<p>Analisando os retornos, pecebemos que quanto maior os lags especificados no teste, mais os residuos se aproximam de um comportamento semelhante a um ruido branco.</p>
<p>com a mesma quantidade de lags, os modelos que utilizam menos lags tem os ruidos com menor autocorrelação, indicando que o modelo mais parcimonioso apresenta um comportamento residual mais estável.</p>
<p><strong>Vamos aplicar o teste de normalidade.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>normalidade_1lag <span class="ot">&lt;-</span> <span class="fu">normality.test</span>(var_1lag)</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(normalidade_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$JB

    JB-Test (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 20.607, df = 10, p-value = 0.02401


$Skewness

    Skewness only (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 3.8041, df = 5, p-value = 0.5779


$Kurtosis

    Kurtosis only (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 16.803, df = 5, p-value = 0.00489</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$jb.mul
$jb.mul$JB

    JB-Test (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 20.607, df = 10, p-value = 0.02401


$jb.mul$Skewness

    Skewness only (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 3.8041, df = 5, p-value = 0.5779


$jb.mul$Kurtosis

    Kurtosis only (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 16.803, df = 5, p-value = 0.00489</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>normalidade_5lags <span class="ot">&lt;-</span> <span class="fu">normality.test</span>(var_5lags)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(normalidade_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$JB

    JB-Test (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 11.351, df = 10, p-value = 0.3308


$Skewness

    Skewness only (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 7.07, df = 5, p-value = 0.2155


$Kurtosis

    Kurtosis only (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 4.2812, df = 5, p-value = 0.5097</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$jb.mul
$jb.mul$JB

    JB-Test (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 11.351, df = 10, p-value = 0.3308


$jb.mul$Skewness

    Skewness only (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 7.07, df = 5, p-value = 0.2155


$jb.mul$Kurtosis

    Kurtosis only (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 4.2812, df = 5, p-value = 0.5097</code></pre>
</div>
</div>
<p>Avaliando os resultados podemos notar que o modelo que considera apenas 1 lag tem um comportamento melhor, porem, os valores discrepantes denotam que o modelo ainda pode ser melhorado.</p>
<p>Verificando os testes de heterocedasticidade.</p>
<p><strong>Modelo com 1 lag</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>heterocedasticidade_1lag <span class="ot">&lt;-</span> <span class="fu">arch.test</span>(var_1lag)</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(heterocedasticidade_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    ARCH (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 570, df = 1125, p-value = 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$arch.mul

    ARCH (multivariate)

data:  Residuals of VAR object var_1lag
Chi-squared = 570, df = 1125, p-value = 1</code></pre>
</div>
</div>
<p><strong>Modelo com 5 lags</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>heterocedasticidade_5lags <span class="ot">&lt;-</span> <span class="fu">arch.test</span>(var_5lags)</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(heterocedasticidade_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    ARCH (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 510, df = 1125, p-value = 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$arch.mul

    ARCH (multivariate)

data:  Residuals of VAR object var_5lags
Chi-squared = 510, df = 1125, p-value = 1</code></pre>
</div>
</div>
<p>Avaliando os p-valores de ambos os modelos, chegamos a conclusao de que a variancia dos residuos e constante ao longo do tempo.</p>
</section>
</section>
<section id="para-explorar-os-resultados-da-modelagem-prossiga-com-as-seguintes-análises" class="level2">
<h2 class="anchored" data-anchor-id="para-explorar-os-resultados-da-modelagem-prossiga-com-as-seguintes-análises">2. Para explorar os resultados da modelagem, prossiga com as seguintes análises:</h2>
<section id="a.-baseando-se-no-modelo-var-estimado-realize-previsões-para-os-próximos-quatro-trimestres-para-cada-uma-das-variáveis-utilizando-a-função-predict." class="level3">
<h3 class="anchored" data-anchor-id="a.-baseando-se-no-modelo-var-estimado-realize-previsões-para-os-próximos-quatro-trimestres-para-cada-uma-das-variáveis-utilizando-a-função-predict.">a. Baseando-se no modelo VAR estimado, realize previsões para os próximos quatro trimestres para cada uma das variáveis utilizando a função predict().</h3>
<ul>
<li>Apresente os intervalos de confiança para essas previsões e discuta a robustez dos resultados, considerando a incerteza associada.</li>
</ul>
<p><strong>Previsões:</strong></p>
<ul>
<li><strong>Previsão dos próximos 4 trimestres para o modelo estimado com 1 lag</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>var_predict_1lag <span class="ot">&lt;-</span> <span class="fu">predict</span>(var_1lag, <span class="at">n.ahead =</span> <span class="dv">4</span>)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(var_predict_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercício-Aula-5---VAR_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_predict_1lag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$PIB_yoy
          fcst     lower    upper       CI
[1,] 2.2062785 -2.866594 7.279151 5.072872
[2,] 1.6317123 -4.732326 7.995751 6.364038
[3,] 1.1244063 -5.827574 8.076386 6.951980
[4,] 0.7609603 -6.414150 7.936071 7.175111

$Selic_diff
            fcst      lower     upper        CI
[1,] -0.05762264 -0.2199493 0.1047040 0.1623267
[2,] -0.04192297 -0.2900447 0.2061988 0.2481218
[3,] -0.03424350 -0.3392453 0.2707583 0.3050018
[4,] -0.02943860 -0.3649869 0.3061097 0.3355483

$IPCA_12M_diff
           fcst     lower    upper       CI
[1,] -0.1349232 -2.743968 2.474122 2.609045
[2,] -0.1129115 -2.866123 2.640300 2.753211
[3,] -0.1146560 -2.905429 2.676117 2.790773
[4,] -0.1012140 -2.901364 2.698936 2.800150

$Dep_Total_yoy_diff
            fcst     lower     upper       CI
[1,] -0.02991045 -7.374836  7.315015 7.344925
[2,]  0.20891396 -8.862587  9.280415 9.071501
[3,]  0.34717711 -9.375825 10.070180 9.723003
[4,]  0.37751144 -9.555838 10.310861 9.933349

$Desemprego_yoy_diff
          fcst     lower    upper       CI
[1,] 1.8211734 -10.27998 13.92233 12.10115
[2,] 1.2924710 -12.56257 15.14751 13.85504
[3,] 0.9523440 -13.41283 15.31752 14.36517
[4,] 0.7369666 -13.79918 15.27311 14.53615</code></pre>
</div>
</div>
<ul>
<li><strong>Previsão dos próximos 4 trimestres para o modelo estimado com 2 lags</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>var_predict_2lags <span class="ot">&lt;-</span> <span class="fu">predict</span>(var_2lags, <span class="at">n.ahead =</span> <span class="dv">4</span>)</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(var_predict_2lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercício-Aula-5---VAR_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_predict_2lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$PIB_yoy
          fcst     lower    upper       CI
[1,] 2.0732921 -2.682825 6.829409 4.756117
[2,] 2.0767293 -4.466901 8.620360 6.543630
[3,] 0.6888655 -6.647935 8.025666 7.336801
[4,] 0.3968667 -7.141159 7.934893 7.538026

$Selic_diff
             fcst      lower      upper        CI
[1,] -0.066583077 -0.2276881 0.09452196 0.1611050
[2,] -0.010642143 -0.2598214 0.23853708 0.2491792
[3,]  0.002192182 -0.3235397 0.32792403 0.3257318
[4,]  0.016168331 -0.3425992 0.37493591 0.3587676

$IPCA_12M_diff
          fcst     lower    upper       CI
[1,] 0.6260891 -1.819985 3.072164 2.446074
[2,] 0.3012757 -2.552579 3.155131 2.853855
[3,] 0.2137200 -2.677537 3.104977 2.891257
[4,] 0.3209487 -2.604571 3.246469 2.925520

$Dep_Total_yoy_diff
           fcst     lower     upper        CI
[1,] -1.0226890  -8.10789  6.062512  7.085201
[2,] -0.8353283 -10.55449  8.883838  9.719166
[3,] -0.2468091 -10.64272 10.149104 10.395913
[4,] -0.5278784 -11.11019 10.054429 10.582308

$Desemprego_yoy_diff
          fcst     lower    upper       CI
[1,] 3.8311007  -7.79435 15.45655 11.62545
[2,] 1.1748231 -13.45525 15.80489 14.63007
[3,] 1.1261151 -13.88237 16.13460 15.00849
[4,] 0.4101508 -14.68225 15.50255 15.09240</code></pre>
</div>
</div>
<p>Previsão dos próximos 4 trimestres para o modelo estimado com 5 lags</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>var_predict_5lags <span class="ot">&lt;-</span> <span class="fu">predict</span>(var_5lags, <span class="at">n.ahead =</span> <span class="dv">4</span>)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(var_predict_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercício-Aula-5---VAR_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_predict_5lags)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$PIB_yoy
           fcst      lower    upper       CI
[1,]  0.4551289  -3.392812 4.303070 3.847941
[2,]  3.0659432  -2.457704 8.589590 5.523647
[3,] -5.6053214 -11.876129 0.665486 6.270807
[4,]  2.9951217  -3.444607 9.434851 6.439729

$Selic_diff
            fcst       lower      upper        CI
[1,] -0.24318064 -0.37150797 -0.1148533 0.1283273
[2,]  0.10626462 -0.08699283  0.2995221 0.1932575
[3,] -0.15920182 -0.43500377  0.1166001 0.2758020
[4,]  0.09901308 -0.19705430  0.3950805 0.2960674

$IPCA_12M_diff
          fcst       lower     upper       CI
[1,]  1.848990  0.02990655 3.6680728 1.819083
[2,] -1.609322 -3.67371809 0.4550731 2.064396
[3,]  1.627935 -0.80688257 4.0627531 2.434818
[4,]  2.431257 -0.18759474 5.0501097 2.618852

$Dep_Total_yoy_diff
          fcst      lower    upper       CI
[1,]  1.430835  -3.829012 6.690682 5.259847
[2,]  2.995459  -3.682712 9.673630 6.678171
[3,]  2.052462  -5.707814 9.812738 7.760276
[4,] -3.108986 -11.240438 5.022467 8.131453

$Desemprego_yoy_diff
           fcst     lower     upper       CI
[1,] -0.7530972 -11.76077 10.254573 11.00767
[2,] -4.2333176 -18.07228  9.605647 13.83896
[3,]  3.3285379 -12.62646 19.283537 15.95500
[4,] -7.6445214 -25.54260 10.253559 17.89808</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Utilize a função fevd() para realizar a decomposição da variância dos erros de previsão. Explique como cada uma das variáveis contribui para a variação nos Depósitos Totais. Discuta a importância dessas contribuições para a compreensão da dinâmica econômica.</li>
</ol>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<ol start="3" type="a">
<li>Utilize a função irf() para calcular as funções de impulso-resposta, com foco nos impactos de choques no PIB sobre os Depósitos Totais. Analise e discuta como esses resultados podem ser utilizados para informar as estratégias de funding da instituição, especialmente em cenários de crescimento econômico. Considere como a instituição pode se preparar para capturar uma maior parcela de mercado de depósitos, e quais estratégias de alocação de recursos podem ser recomendadas com base nos resultados obtidos.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>